2022-04-26 11:43:16,430 INFO    MainThread:2409265 [wandb_setup.py:_flush():75] Loading settings from /home/rishabh/.config/wandb/settings
2022-04-26 11:43:16,430 INFO    MainThread:2409265 [wandb_setup.py:_flush():75] Loading settings from /home/rishabh/practice_runs/cs4243-project/wandb/settings
2022-04-26 11:43:16,430 INFO    MainThread:2409265 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-04-26 11:43:16,431 INFO    MainThread:2409265 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-04-26 11:43:16,431 INFO    MainThread:2409265 [wandb_init.py:_log_setup():437] Logging user logs to /home/rishabh/practice_runs/cs4243-project/wandb/run-20220426_114316-2zip8jli/logs/debug.log
2022-04-26 11:43:16,431 INFO    MainThread:2409265 [wandb_init.py:_log_setup():438] Logging internal logs to /home/rishabh/practice_runs/cs4243-project/wandb/run-20220426_114316-2zip8jli/logs/debug-internal.log
2022-04-26 11:43:16,431 INFO    MainThread:2409265 [wandb_init.py:init():471] calling init triggers
2022-04-26 11:43:16,431 INFO    MainThread:2409265 [wandb_init.py:init():475] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'epochs': 20, 'batch_size': 512}
2022-04-26 11:43:16,431 INFO    MainThread:2409265 [wandb_init.py:init():491] re-initializing run, found existing run on stack: 2l39mejr
2022-04-26 11:43:16,433 INFO    MainThread:2409265 [wandb_run.py:_finish():1685] finishing run rish-16/cs4243-project/2l39mejr
2022-04-26 11:43:16,433 INFO    MainThread:2409265 [jupyter.py:save_history():435] not saving jupyter history
2022-04-26 11:43:16,433 INFO    MainThread:2409265 [jupyter.py:save_ipynb():377] not saving jupyter notebook
2022-04-26 11:43:16,433 INFO    MainThread:2409265 [wandb_init.py:_jupyter_teardown():369] cleaning up jupyter logic
2022-04-26 11:43:16,433 INFO    MainThread:2409265 [wandb_run.py:_atexit_cleanup():1866] got exitcode: 0
2022-04-26 11:43:16,434 INFO    MainThread:2409265 [wandb_run.py:_restore():1838] restore
2022-04-26 11:43:17,277 INFO    MainThread:2409265 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 869
  total_bytes: 869
}

2022-04-26 11:43:17,635 INFO    MainThread:2409265 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 869
  total_bytes: 869
}

2022-04-26 11:43:17,737 INFO    MainThread:2409265 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 869
  total_bytes: 9531
}

2022-04-26 11:43:17,840 INFO    MainThread:2409265 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 869
  total_bytes: 9531
}

2022-04-26 11:43:17,942 INFO    MainThread:2409265 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 9531
  total_bytes: 9531
}

2022-04-26 11:43:18,045 INFO    MainThread:2409265 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 9531
  total_bytes: 9531
}

2022-04-26 11:43:18,146 INFO    MainThread:2409265 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 9531
  total_bytes: 9531
}

2022-04-26 11:43:18,248 INFO    MainThread:2409265 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 9531
  total_bytes: 9531
}

2022-04-26 11:43:18,350 INFO    MainThread:2409265 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 9531
  total_bytes: 9531
}

2022-04-26 11:43:18,452 INFO    MainThread:2409265 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 9531
  total_bytes: 9531
}

2022-04-26 11:43:19,237 INFO    MainThread:2409265 [wandb_run.py:_on_finish():1995] got exit ret: file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 9531
  total_bytes: 9531
}

2022-04-26 11:43:19,787 INFO    MainThread:2409265 [wandb_run.py:_on_finish():1995] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
}
pusher_stats {
  uploaded_bytes: 9531
  total_bytes: 9531
}
local_info {
}

2022-04-26 11:43:21,029 INFO    MainThread:2409265 [wandb_run.py:_footer_history_summary_info():3102] rendering history
2022-04-26 11:43:21,029 INFO    MainThread:2409265 [wandb_run.py:_footer_history_summary_info():3134] rendering summary
2022-04-26 11:43:21,031 INFO    MainThread:2409265 [wandb_run.py:_footer_sync_info():3057] logging synced files
2022-04-26 11:43:21,035 INFO    MainThread:2409265 [wandb_init.py:init():524] starting backend
2022-04-26 11:43:21,035 INFO    MainThread:2409265 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-04-26 11:43:21,037 INFO    MainThread:2409265 [backend.py:ensure_launched():217] starting backend process...
2022-04-26 11:43:21,298 INFO    MainThread:2409265 [backend.py:ensure_launched():222] started backend process with pid: 2417703
2022-04-26 11:43:21,300 INFO    MainThread:2409265 [wandb_init.py:init():533] backend started and connected
2022-04-26 11:43:21,324 INFO    MainThread:2409265 [wandb_run.py:_label_probe_notebook():1084] probe notebook
2022-04-26 11:43:21,325 INFO    MainThread:2409265 [wandb_init.py:init():597] updated telemetry
2022-04-26 11:43:21,888 INFO    MainThread:2409265 [wandb_init.py:init():628] communicating run to backend with 30 second timeout
2022-04-26 11:43:22,825 INFO    MainThread:2409265 [wandb_run.py:_on_init():1923] communicating current version
2022-04-26 11:43:22,865 INFO    MainThread:2409265 [wandb_run.py:_on_init():1927] got version response 
2022-04-26 11:43:22,866 INFO    MainThread:2409265 [wandb_init.py:init():659] starting run threads in backend
2022-04-26 11:43:25,151 INFO    MainThread:2409265 [wandb_run.py:_console_start():1897] atexit reg
2022-04-26 11:43:25,151 INFO    MainThread:2409265 [wandb_run.py:_redirect():1770] redirect: SettingsConsole.WRAP
2022-04-26 11:43:25,151 INFO    MainThread:2409265 [wandb_run.py:_redirect():1807] Wrapping output streams.
2022-04-26 11:43:25,154 INFO    MainThread:2409265 [wandb_run.py:_redirect():1831] Redirects installed.
2022-04-26 11:43:25,154 INFO    MainThread:2409265 [wandb_init.py:init():684] run started, returning control to user process
2022-04-26 11:58:34,647 INFO    MainThread:2409265 [wandb_setup.py:_flush():75] Loading settings from /home/rishabh/.config/wandb/settings
2022-04-26 11:58:34,648 INFO    MainThread:2409265 [wandb_setup.py:_flush():75] Loading settings from /home/rishabh/practice_runs/cs4243-project/wandb/settings
2022-04-26 11:58:34,648 INFO    MainThread:2409265 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-04-26 11:58:34,648 INFO    MainThread:2409265 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-04-26 11:58:34,649 INFO    MainThread:2409265 [wandb_init.py:_log_setup():437] Logging user logs to /home/rishabh/practice_runs/cs4243-project/wandb/run-20220426_115834-10dopjlx/logs/debug.log
2022-04-26 11:58:34,649 INFO    MainThread:2409265 [wandb_init.py:_log_setup():438] Logging internal logs to /home/rishabh/practice_runs/cs4243-project/wandb/run-20220426_115834-10dopjlx/logs/debug-internal.log
2022-04-26 11:58:34,650 INFO    MainThread:2409265 [wandb_init.py:_jupyter_setup():387] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f6e5efd7a90>
2022-04-26 11:58:34,651 INFO    MainThread:2409265 [wandb_init.py:init():471] calling init triggers
2022-04-26 11:58:34,652 INFO    MainThread:2409265 [wandb_init.py:init():475] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'epochs': 20, 'batch_size': 512}
2022-04-26 11:58:34,652 INFO    MainThread:2409265 [wandb_init.py:init():491] re-initializing run, found existing run on stack: 2zip8jli
2022-04-26 11:58:34,696 ERROR   MainThread:2409265 [wandb_init.py:init():1022] error
Traceback (most recent call last):
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 995, in init
    run = wi.init()
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 503, in init
    self._wl._global_run_stack[-1].finish()
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 256, in wrapper
    return func(self, *args, **kwargs)
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 222, in wrapper
    return func(self, *args, **kwargs)
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1678, in finish
    return self._finish(exit_code, quiet)
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1684, in _finish
    tel.feature.finish = True
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/lib/telemetry.py", line 41, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 572, in _telemetry_callback
    self._telemetry_flush()
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 583, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 74, in _publish_telemetry
    self._publish(rec)
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface_queue.py", line 49, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2022-04-26 11:58:57,529 ERROR   MainThread:2409265 [wandb_init.py:init():1022] error
Traceback (most recent call last):
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 992, in init
    wi.setup(kwargs)
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 175, in setup
    tel.feature.set_init_tags = True
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/lib/telemetry.py", line 41, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 572, in _telemetry_callback
    self._telemetry_flush()
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 583, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 74, in _publish_telemetry
    self._publish(rec)
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface_queue.py", line 49, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2022-04-26 11:59:53,482 ERROR   MainThread:2409265 [wandb_init.py:init():1022] error
Traceback (most recent call last):
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 992, in init
    wi.setup(kwargs)
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 175, in setup
    tel.feature.set_init_tags = True
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/lib/telemetry.py", line 41, in __exit__
    self._run._telemetry_callback(self._obj)
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 572, in _telemetry_callback
    self._telemetry_flush()
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 583, in _telemetry_flush
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 74, in _publish_telemetry
    self._publish(rec)
  File "/home/rishabh/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface_queue.py", line 49, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2022-04-26 12:01:30,394 INFO    MainThread:2409265 [wandb_run.py:_atexit_cleanup():1866] got exitcode: 0
2022-04-26 12:01:30,395 INFO    MainThread:2409265 [wandb_run.py:_restore():1838] restore
